### ISSUE TITLE
is the current security model of the official opam-repository so bad that you have to do this?

### ISSUE THREAD

**Issue by UnixJunkie** [hannesm/jackline-opam#1]
I.e. create a separated opam repository.

**Comment by hannesm** [comment]
@UnixJunkie since I started to develop in OCaml I found the lack of signing in opam a real deficiency.  That's why I stepped up as early as 2015 and proposed together with Louis a [signing the opam repository](https://opam.ocaml.org/blog/Signing-the-opam-repository/) mechanism, in 2016 revised [as a OCaml workshop talk](https://github.com/hannesm/conex-paper/raw/master/paper.pdf), and in spring 2017 revised together with Justin Cappos ([read some more information here](https://ssl.engineering.nyu.edu/blog/2017-05-15-conex)).  See also some [post](https://hannes.nqsb.io/Posts/Conex) about an early 2017 prototype (based on the 2016 workshop talk).

So,yes, in order to evaluate my current prototype properly my approach was to start with a toy repository (see https://github.com/hannesm/testrepo), now slowly advancing to larger repositories -- before declaring it "ready for use with the main opam-repository".  This also implies me trying to convince others to try this out, which means they need to get access to this repository.  I'm still undecided whether this repository will disappear once opam-repository uses conex.

But, what is wrong with smaller opam-repositories?

**Comment by hannesm** [comment]
Oh, and back to your initial question/topic: the short answer is yes.  There is _no_ security model of the official opam-repository.  You have to trust: lots of individuals (who merge PRs), the GitHub servers (where the repo is synced from), but also a random rackspace-hosted server named opam.ocaml.org (where clients download the repository from).

**Comment by cfcs** [comment]
@UnixJunkie This is a repository to test out integration of `conex` into `opam2`, in preparation for it to be included with the default release.

This is not a hostile fork of any kind, just to clear that up.
If you see the opam2 installation instructions, they also mention this work.

The answer to your question is **there currently is no security model of the official repository**, which is why we should all thank @hannesm for the massive amount of work he has undertaken to mitigate that problem, and to make it upstreamable.

**Comment by UnixJunkie** [comment]
Thanks for the info.
If the opam repository was supporting url files with more than just an md5sum, for example a sha256 sum
plus a maintainer's cryptographic signature of the released tarball, I would feel better already.

**Comment by hannesm** [comment]
> If the opam repository was supporting url files with more than just an md5sum, for example a sha256 sum plus a maintainer's cryptographic signature of the released tarball, I would feel better already.

the former is supported by opam2! :)
the latter requires some form of public key infrastructure, since you'd like to ensure that "a maintainer" is really the one in charge (and someone has to decide on this) for the given "released tarball".
also, keep in mind that the opam files may include (a) arbitrary patch files and (b) build instructions (which are morally shell commands), both are risks, and thus this data needs to be signed as well.

I'm not entirely sure what you mean with `maintainer` above - for me (well, conex design) the signatures should be from the individual `developers` who write software and publish releases -- and the `repository maintainers` need to sign which `developer(s)` is/are in charge of each package.

**Comment by cfcs** [comment]
@UnixJunkie The cryptographic signature part is *exactly* what Hannes is working on here. :)

**Comment by UnixJunkie** [comment]
By maintainer, I mean the developer of the software, who makes a release and should sign the corresponding tarball.
Also, should we push for reproducible builds in opam?
Some Linux distro require this.

**Comment by cfcs** [comment]
@UnixJunkie with the CONEX design, there are several layers of signatures (developer; distributor; external auditing), and instead of having a single signature from each of these layers, you can decide on a *"quorum"*/threshold, like *2-out-of-N* signatures to agree on something. You can also potentially configure it to require proof of entry into an append-only log (provided someone makes a signing bot like that).
If the developer is the only person doing the signing, this means that a compromised/malicious developer can serve special-tailored backdoors to specific people. That is much less likely to get detected than if *everyone* gets the same backdoor. Reproducible builds also help in this regard.
